apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xdv28lq0o-nodejs 
  janus-idp.io/tekton: xdv28lq0o-nodejs
  backstage.io/kubernetes-id: xdv28lq0o-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xdv28lq0o-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml